apiVersion: v1
kind: ConfigMap
metadata:
  name: lifesub-web-config
  namespace: dg0413-lifesub-ns
data:
  runtime-env.js: |
    window.__runtime_config__ = {
      MEMBER_URL: 'http://dg0413.20.249.191.180.nip.io/api/auth',
      MYSUB_URL: 'http://dg0413.20.249.191.180.nip.io/api/mysub', 
      RECOMMEND_URL: 'http://dg0413.20.249.191.180.nip.io/api/recommend'
    };
